### ISSUE TITLE
Accept your invites to gain write access to this repo

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/eeb430.2017.Python#5]
Hi guys,
Great job uploading the pull requests (PR)! If you wonder why only @C-Rouleau gets a green check mark when he approves a PR, it is because the rest of you have yet to accept your invites to gain write privileges to this repo. ~~Unfortunately, this also means that I cannot tag you by name in this issue, so @C-Rouleau, could you forward a link to this issue to your teammates via whichever platform you guys use for communication?~~ There is not hurry with this, we can do it on Tuesday also.

#### To accept the repository invite
To the right in the black bar on the top, there is a small bell (potentially with a blue dot on it), click it. This is where you get notifications if something has happened (you will also get an email if you have set that up). If you don't see the invite right away, please click "All notifications" and it should be there. Let me know if it is not and I will send you a new one.

**Comment by QuLogic** [comment]
You can certainly tag @bendownerbartholomew, @faridasamadzada, and @Smooj. Their names just won't auto-complete.

**Comment by joelostblom** [comment]
Great, I learnt something!

**Comment by Smooj** [comment]
I don't see a blue bell in the black bar

**Comment by joelostblom** [comment]
The bell is grey, possibly with a blue dot. You can also go here directly https://github.com/notifications

**Comment by Smooj** [comment]
Can you send another email? I don't seem to have any notifications

**Comment by joelostblom** [comment]
I just resent it to the three of you, let me know if you still can't see it.
