### ISSUE TITLE
Can't install the package "scales"

### ISSUE THREAD

**Issue by Smooj** [UofTCoders/eeb430.2017.Python#6]
Hey,

Our team wants to change the colour palette of our theme and we want to use scale_colour_colorblind but we can't install the package scales on R. R keeps telling us that there is an error loading the package and that we need to restart R.

**Comment by lwjohnst86** [comment]
Yeay! Good to hear! The package `scales` should already be installed since it is I believe part of ggplot2. However, the package I think actually need is `ggthemes`, which contains the `scale_colour_colorblind` function. So you'll need to install that package.

**Comment by joelostblom** [comment]
We needed to create a list of the theme and `scale_color_colorblind` as per https://stackoverflow.com/questions/35559303/r-how-to-add-scale-functio-to-a-theme-object-in-ggplot2.
